<h3 style='color:purple'>Exercise</h3>

1. Load heart disease dataset in pandas dataframe
1. Remove outliers using Z score. Usual guideline is to remove anything that has Z score > 3 formula or Z score < -3
1. Convert text columns to numbers using label encoding and one hot encoding
1. Apply scaling
1. Build a classification model using various methods (SVM, logistic regression, random forest) and check which model gives you the best accuracy
1. Now use PCA to reduce dimensions, retrain your model and see what impact it has on your model in terms of accuracy. Keep in mind that many times doing PCA reduces the accuracy but computation is much lighter and that's the trade off you need to consider while building models in real life

In [112]:
import pandas as pd

df = pd.read_csv('heart.csv')
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [113]:
z_scores = (df.Cholesterol - df.Cholesterol.mean()) / df.Cholesterol.std()
df_no_outliers = df[(z_scores > -3) & (z_scores < 3)]
df_no_outliers.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [114]:
df_new = pd.get_dummies(df_no_outliers, drop_first=True)
df_new.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,True,True,False,False,True,False,False,False,True
1,49,160,180,0,156,1.0,1,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,0,True,True,False,False,False,True,False,False,True
3,48,138,214,0,108,1.5,1,False,False,False,False,True,False,True,True,False
4,54,150,195,0,122,0.0,0,True,False,True,False,True,False,False,False,True

In [115]:
X = df_new.drop('HeartDisease', axis='columns')
y = df_new.HeartDisease

In [116]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaled = scaler.fit_transform(X)
x_scaled

array([[-1.43736051,  0.40855699,  0.85062571, ..., -0.82395333,
        -0.9989077 ,  1.14736903],
       [-0.4804758 ,  1.4885213 , -0.16377238, ..., -0.82395333,
         1.00109349, -0.87155917],
       [-1.75632207, -0.13142516,  0.79478728, ..., -0.82395333,
        -0.9989077 ,  1.14736903],
       ...,
       [ 0.37008838, -0.13142516, -0.61978619, ...,  1.21366098,
         1.00109349, -0.87155917],
       [ 0.37008838, -0.13142516,  0.35738627, ..., -0.82395333,
         1.00109349, -0.87155917],
       [-1.65000155,  0.30056056, -0.2103044 , ..., -0.82395333,
        -0.9989077 ,  1.14736903]])

In [124]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=30)

In [126]:
X.shape

(915, 15)

In [121]:
from sklearn.decomposition import PCA

pca = PCA(0.95)
X_pca = pca.fit_transform(X)
X_pca

array([[ 93.58815985,  29.20646448],
       [-15.84856663,  13.61209317],
       [ 83.00603096, -38.34040004],
       ...,
       [-67.84608988, -17.25133047],
       [ 40.4754608 ,  33.44762003],
       [-20.14342739,  37.1645631 ]])

In [122]:
X_pca.shape

(915, 2)

In [119]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=30)

In [120]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier()
model_rf.fit(X_train_pca, y_train)
model_rf.score(X_test_pca, y_test)

0.6885245901639344